### PR TITLE
Add simple function generators

### PR DESCRIPTION
**Pull request by cmeeren**
As far as I'm concerned this is ready to be merged.

### CODE REVIEW

**Comment by moodmosaic** [comment]
Ugh, this one shows conflicts.

**Comment by cmeeren** [comment]
No worries, I'll rebase on master (this was expected since I made several parallel PRs based on master).

**Comment by moodmosaic** [comment]
Yes, I've merged #8, so you'll have to pull the latest from `master`.

**Comment by cmeeren** [comment]
I think it's good now.

**Comment by moodmosaic** [comment]
Manually merged in https://github.com/hedgehogqa/fsharp-hedgehog-experimental/commit/c4860580275c23a80080497b361286278bfbf06d via `git merge --no-ff`.

**Comment by cmeeren** [comment]
> Manually merged in `c486058` via `git merge --no-ff`.

Was it something I did in the process of rebasing? Should I ideally have done something differently?

**Comment by moodmosaic** [comment]
This makes the history looks tidy, that's all :neckbeard: 

image

You didn't do something wrong, it's just that GitHub doesn't have this as an option (yet) when merging a pull request.

**Pull request closed without merging**
