### PR TITLE
Add misc combinators

### PR DESCRIPTION
**Pull request by cmeeren**
Waiting with other PRs until this is merged.

### CODE REVIEW

**Comment by moodmosaic** [comment]
@cmeeren 
>Waiting with other PRs until this is merged.

You mean, we should look at this PR once you add more PRs?

**Comment by cmeeren** [comment]
> You mean, we should look at this PR once you add more PRs?

No, I am waiting to create more PRs until after this one is merged.

**Comment by moodmosaic** [comment]
@cmeeren, this one looks good as-is, and perhaps we can merge it(?) FWIW, I linked all related items in https://github.com/hedgehogqa/fsharp-hedgehog-experimental/issues/5.

**Comment by cmeeren** [comment]
Sure, merge away :)

**Comment by moodmosaic** [comment]
Do you want me to put [those other ones](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/issues/5) in, by the way?

**Comment by cmeeren** [comment]
If you're talking about more generators, then no, I've deliberately left them out of this PR and will include them in separate PRs.

**Comment by moodmosaic** [comment]
@cmeeren, done 🎉 Looking forward to those other PRs so we can release this on NuGet.

**Comment by cmeeren** [comment]
Will have them up in a jiffy.

**Pull request merged**
