### PR TITLE
Isolate mutations from calls to Gen.bind

### PR DESCRIPTION
**Pull request by TysonMN**
Revolves #52

...by working around https://github.com/hedgehogqa/fsharp-hedgehog/issues/192.

@dharmaturtle, after this completes and a new version is released, you should update `Hedgehog.Xunit` to require this new version and make a release so that users get this bug fix.

### CODE REVIEW

**Comment by TysonMN** [comment]
The string/keyword `mutable` no longer occurs in the main project.  There are still mutations though such as those in `shuffle` and `shuffleCase` (c.f. https://github.com/hedgehogqa/fsharp-hedgehog/issues/192).  I will fix those soon in a separate PR.

**Comment by TysonMN** [comment]
Quoting @cmeeren from https://github.com/hedgehogqa/fsharp-hedgehog/issues/192#issuecomment-573132414
> ...should I prioritize implementing them without immutability? (That might impact performance, so I'd rather not.)

I think correctness is more important than efficiency, so I think we should merge this PR because it fixes bugs and worry about performance another day.

**Comment by cmeeren** [comment]
Thanks a lot! I don't have the capacity to do a thorough review of this. If you think it is ready to go, I'll merge and release a new version. Could you also update the changelog and fsproj version?

**Comment by cmeeren** [comment]
Alternatively, if you'd rather wait to release this until other PRs are merged, don't increment the fsproj version (that triggers a release).

**Comment by cmeeren** [comment]
> I think correctness is more important than efficiency

I agree. I wanted to hold out for a couple of days in case it was fixed upstream, and then I forgot all about it.

**Comment by cmeeren** [comment]
And if this closes #52, could you add that to the OP so it's done automatically?

**Review by dharmaturtle — APPROVED** [review]

**Comment by TysonMN** [comment]
Oh, I think the issue with efficiency was that your immutable code was quadratic (due to repeatedly concatenating a single character to a string accumulator).  Pretty sure the runtime of my code is linear.

**Comment by TysonMN** [comment]
> Alternatively, if you'd rather wait to release this until other PRs are merged, don't increment the fsproj version (that triggers a release).

Let's wait until I also fix the shuffle functions.

**Comment by TysonMN** [comment]
> I don't have the capacity to do a thorough review of this. If you think it is ready to go, I'll merge [...]

 Yes, it's ready. In particular, I first added tests that fail send now they pass.

**Comment by cmeeren** [comment]
Excellent! Could you also update the changelog (repo root) and fsproj version?

**Comment by TysonMN** [comment]
I updated the changelog.

Can we wait to release a new version until after I fix the same bugs in `shuffle` and `shuffleCase`?

**Comment by TysonMN** [comment]
(Force pushed to improve the names of the tests)

**Comment by cmeeren** [comment]
Excellent, thank you very much!

**Pull request merged**
