### PR TITLE
added entry to changelog about new support for multidimensional arrays to GenX.auto

### PR DESCRIPTION
**Pull request by TysonMN**

### CODE REVIEW

**Comment by cmeeren** [comment]
Thanks!

**Comment by cmeeren** [comment]
@TysonMN, were there more outstanding issues before release?

**Comment by TysonMN** [comment]
No local issues, but I expect Hedgehog to release 0.11 soon, so I recommend waiting for that before releasing.

**Comment by cmeeren** [comment]
Sure!

**Pull request merged**
