### PR TITLE
Rename Gen module to GenX

### PR DESCRIPTION
**Pull request by cmeeren**
Before merging: Should I also rename `Gen.fs` and `GenTests.fs` to `GenX.fs` and `GenXTests.fs`?

### CODE REVIEW

**Comment by moodmosaic** [comment]
Perhaps we should leave the files as-is for now, until we sort out the final name?

**Comment by cmeeren** [comment]
Sure, go ahead and merge. :)

**Comment by cmeeren** [comment]
If you can merge this quickly, I can pull the updated master and create a new auto-gen PR during the next hour. Otherwise you'll probably have to wait until tonight or tomorrow.

**Comment by moodmosaic** [comment]
Merged in cb21ece.

**Pull request closed without merging**
