### PR TITLE
Multidimensional arrays

### LINKED ISSUE #50: Support for Array.Rank greater than 1
Why isn't there support when [`Array.Rank`](https://docs.microsoft.com/en-us/dotnet/api/system.array.rank) is greater than `1`?  Is there some fundamental technical difficulty or is it just that sufficient time/effort was never spent to implement that case?

https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/439159cd7cbf99b793bae3eac59dd02a9192d7a8/src/Hedgehog.Experimental/Gen.fs#L421-L431

### PR DESCRIPTION
**Pull request by TysonMN**
Resolves #50

This is a draft PR because I don't have it working yet.

The code seems correct to me, and the three tests that previously passed because of the one-dimensional code now pass with the multidimensional code.

However, the shrinking is not working correctly.  It is not working in the same why that I just fixed in the previous three PRs.

Please don't feel like you need to review this @cmeeren.  I think @dharmaturtle is going to take a look.

### CODE REVIEW

**Comment by TysonMN** [comment]
Those are not exactly the right tests either, so I expect some of them to fail right now.

**Comment by TysonMN** [comment]
@dharmaturtle, I just pushed a commit where I try to log the array length, but there is no link to output in the test results.  Why??

2021-09-04_21-45-18_680_devenv

**Comment by dharmaturtle** [comment]
No idea. Didn't try to hard to fix it - I use [my own StackOverflow answer](https://stackoverflow.com/a/56334043) in situations where I don't have NCrunch. [This commit](https://github.com/dharmaturtle/fsharp-hedgehog-experimental/commit/580530804196e76152a332bc9418b84b84808e4b) yields this output:

image

**Comment by TysonMN** [comment]
Excellent.  Clearly you have shown me that before, I because I have updated it! ;)

**Comment by TysonMN** [comment]
I still don't understand.

- 3 tests
- 0 shrinks
- 5 calls to `printfn`
- The displayed failing input has length 5 but that value was the third output, not the last / fifth

None of that makes sense.  Maybe the displayed value matches the call to `println` as indicated by the number of tests.

2021-09-04_22-56-23_681_devenv

**Comment by dharmaturtle** [comment]
I'm ignoring the test/shrink count for now.

I removed the `gen` computation expression completely. Unfortunately, the non-optimal shrinking persists.

Referring to our Slack conversation, I feel like this continues to indicate that it tries to:
1. shrink the first gen (lengths)
2. gives up after a bit
3. tries to shrink the second gen (data)
4. then calls it quits _without reattempting to shrink the first gen_
5. which causes the bug. If the first gen is shrunk to `length=3` and the second gen is shrunk to `data=[1 0 0]`, it _doesn't_ revisit the first gen to shrink to to `length=2` (causing the data to be (shrunk? truncated?) to `[1 0]`).

image

**Comment by cmeeren** [comment]
Unsubscribing to reduce inbox noise; please ping me whenever you want my attention. 😊

**Comment by TysonMN** [comment]
Yes, that is an accurate description of the behavior.  I am going to connect to Hedgehog source in a few minutes and break while shrinking (which happens in `Property.tskeSmallest`).

**Comment by TysonMN** [comment]
Oh, just like https://github.com/hedgehogqa/fsharp-hedgehog/issues/223, I think the explanation is simply that the shrinking is getting stuck in a local optima.

It does try to shrink the length first generator (e.g. the length of the 1D array) _while not searching any of the other generators_.  If the initial failing input doesn't already have length 2, then it generates an input with length 2, but _it (typically) won't be a prefix of the original failing input list_.

So I think I was just confused about the behavior.  I was expecting it to obtain the minimal failing input, but I was wrong.

**Comment by TysonMN** [comment]
Now that we got this figured out (which, again, was must me being confused instead of their being a problem with this code), I will close this PR and open a new one so that nobody has to read and stream of consciousness above.

**Pull request closed without merging**
